---
AWSTemplateFormatVersion: 2010-09-09

Description: 'Provisions HA Grafana Security and Exports'

Parameters:
  Environment:
    Type: String
  

Resources:
  GrafanaServiceSG:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: !Sub 'Grafana database security group (${Environment})'
      VpcId: 
        Fn::ImportValue:
          Fn::Sub: ${Environment}-vpc

Outputs:
  SecurityGroupId:
    Export:
      Name: !Sub ${Environment}-grafana-sg-id
    Value: !GetAtt GrafanaServiceSG.GroupId
