---
AWSTemplateFormatVersion: 2010-09-09

Description: 'Grafana Service RecordSet'

Parameters:
  Environment:
    Type: 'String'
  HostedZoneId:
    Type: 'String'
  DomainName:
    Type: 'String'

Resources:
  RecordSet:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      AliasTarget:
        DNSName: 
          Fn::ImportValue: !Sub '${Environment}-grafana-service-lb-dns'
        HostedZoneId:
          Fn::ImportValue: !Sub '${Environment}-grafana-service-lb-hosted-zone-id'
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: 'A'

Outputs:
  DNSName:
    Value: !Ref 'RecordSet'
    Export:
      Name: !Join ['-', [!Ref 'Environment', 'grafana', 'service', 'domain']]